// Extended catalogue, modelled on the Khurja pottery range (tableware, tea
// sets, pickle/kitchen jars, planters, vases, hand-painted decorative plates).
// Names, prices and copy are our own; photos are CC0 — see public/products/CREDITS.md.
// New products start without ratings: those come from real customer reviews.

export type SeedProduct = {
  name: string;
  slug: string;
  code: string;
  category: string;
  price: number;
  mrp: number;
  stock: number;
  rating?: number;
  reviewCount?: number;
  isFeatured: boolean;
  description: string;
  image: string;
  specifications: [string, string][];
};

const img = (slug: string) => `/products/${slug}.jpg`;

export const newCategoryDescriptions: Record<string, string> = {
  "Tea Sets & Teapots": "Teapots, tea sets and pourers for slow mornings and warm evenings.",
  "Jars & Storage": "Glazed jars and canisters for pickles, spices, tea and pantry staples.",
  "Planters & Pots": "Ceramic planters for indoor greens, succulents and balcony gardens.",
  "Vases & Décor": "Vases and décor pieces that bring colour and craft to any room.",
  "Decorative Plates": "Hand-painted plates in the Khurja tradition, made for display and gifting.",
};

export const moreProducts: SeedProduct[] = [
  // ---------------------------------------------------------------- Cups & Mugs
  {
    name: "Classic White Mug Pair",
    slug: "classic-white-mug-pair",
    code: "AC-CM-002",
    category: "Cups & Mugs",
    price: 549,
    mrp: 699,
    stock: 60,
    isFeatured: false,
    description: "Two clean, glossy white mugs with a comfortable handle — the everyday essential for tea, coffee and hot chocolate.",
    image: img("classic-white-mug-pair"),
    specifications: [["Material", "Ceramic"], ["Capacity", "350 ml each"], ["Pieces", "Set of 2"], ["Finish", "Glossy White"], ["Microwave Safe", "Yes"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Speckled Stoneware Mug",
    slug: "speckled-stoneware-mug",
    code: "AC-CM-003",
    category: "Cups & Mugs",
    price: 399,
    mrp: 499,
    stock: 45,
    isFeatured: false,
    description: "A sturdy stoneware mug with a soft speckled glaze and a straight, hand-thrown profile that sits well in the hand.",
    image: img("speckled-stoneware-mug"),
    specifications: [["Material", "Stoneware"], ["Capacity", "300 ml"], ["Finish", "Speckled Matte"], ["Microwave Safe", "Yes"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Matte Black Coffee Mug",
    slug: "matte-black-coffee-mug",
    code: "AC-CM-004",
    category: "Cups & Mugs",
    price: 349,
    mrp: 449,
    stock: 50,
    isFeatured: false,
    description: "A modern matte black mug with a glossy interior, sized for a generous morning coffee.",
    image: img("matte-black-coffee-mug"),
    specifications: [["Material", "Ceramic"], ["Capacity", "320 ml"], ["Finish", "Matte Black / Glossy Inside"], ["Microwave Safe", "Yes"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Gulbahar Hand-Painted Mug",
    slug: "gulbahar-hand-painted-mug",
    code: "AC-CM-005",
    category: "Cups & Mugs",
    price: 449,
    mrp: 549,
    stock: 30,
    isFeatured: true,
    description: "Brush-painted floral panels in red and green over a white glaze — a small piece of traditional pottery art for your daily chai.",
    image: img("gulbahar-hand-painted-mug"),
    specifications: [["Material", "Ceramic"], ["Capacity", "300 ml"], ["Finish", "Hand-Painted, Glazed"], ["Care", "Hand wash recommended"]],
  },
  {
    name: "Mocha Swirl Mug",
    slug: "mocha-swirl-mug",
    code: "AC-CM-006",
    category: "Cups & Mugs",
    price: 479,
    mrp: 599,
    stock: 25,
    isFeatured: false,
    description: "Marbled swirls of blue, rust and cream between banded rims — no two mugs are exactly alike.",
    image: img("mocha-swirl-mug"),
    specifications: [["Material", "Ceramic"], ["Capacity", "350 ml"], ["Finish", "Marbled Glaze"], ["Care", "Hand wash recommended"]],
  },
  {
    name: "Midnight Cup & Saucer Set",
    slug: "midnight-cup-saucer-set",
    code: "AC-CM-007",
    category: "Cups & Mugs",
    price: 799,
    mrp: 999,
    stock: 35,
    isFeatured: false,
    description: "Deep black cups with cream interiors and matching saucers, stackable for easy storage.",
    image: img("midnight-cup-saucer-set"),
    specifications: [["Material", "Ceramic"], ["Capacity", "200 ml per cup"], ["Pieces", "2 Cups + 2 Saucers"], ["Finish", "Glossy Black"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Honey Glaze Cup & Saucer",
    slug: "honey-glaze-cup-saucer",
    code: "AC-CM-008",
    category: "Cups & Mugs",
    price: 399,
    mrp: 499,
    stock: 40,
    isFeatured: false,
    description: "A warm honey-toned glaze on a wide cup and saucer — made for slow evening tea.",
    image: img("honey-glaze-cup-saucer"),
    specifications: [["Material", "Ceramic"], ["Capacity", "220 ml"], ["Pieces", "1 Cup + 1 Saucer"], ["Finish", "Honey Glaze"]],
  },
  {
    name: "Everyday Espresso Cup Set",
    slug: "everyday-espresso-cup-set",
    code: "AC-CM-009",
    category: "Cups & Mugs",
    price: 899,
    mrp: 1099,
    stock: 30,
    isFeatured: false,
    description: "Four white espresso cups with saucers — thick walls keep coffee hot for longer.",
    image: img("everyday-espresso-cup-set"),
    specifications: [["Material", "Porcelain"], ["Capacity", "90 ml per cup"], ["Pieces", "4 Cups + 4 Saucers"], ["Finish", "Glossy White"], ["Dishwasher Safe", "Yes"]],
  },

  // --------------------------------------------------------- Tea Sets & Teapots
  {
    name: "Matte Black Teapot",
    slug: "matte-black-teapot",
    code: "AC-TS-001",
    category: "Tea Sets & Teapots",
    price: 1299,
    mrp: 1599,
    stock: 20,
    isFeatured: false,
    description: "A rounded teapot in deep black with a red-brown rim and a drip-free spout.",
    image: img("matte-black-teapot"),
    specifications: [["Material", "Ceramic"], ["Capacity", "900 ml"], ["Finish", "Matte Black"], ["Serves", "4–5 cups"]],
  },
  {
    name: "Celadon Tea Set",
    slug: "celadon-tea-set",
    code: "AC-TS-002",
    category: "Tea Sets & Teapots",
    price: 2499,
    mrp: 2999,
    stock: 12,
    isFeatured: true,
    description: "A soft sage-green celadon teapot with matching cups and saucers for serving tea to guests.",
    image: img("celadon-tea-set"),
    specifications: [["Material", "Stoneware"], ["Teapot Capacity", "800 ml"], ["Pieces", "Teapot + 4 Cups + 4 Saucers"], ["Finish", "Celadon Glaze"]],
  },
  {
    name: "Phoolwari Hand-Painted Teapot",
    slug: "phoolwari-hand-painted-teapot",
    code: "AC-TS-003",
    category: "Tea Sets & Teapots",
    price: 1799,
    mrp: 2199,
    stock: 15,
    isFeatured: true,
    description: "Botanical sprays painted by hand on a creamy white body, finished with a clear glaze.",
    image: img("phoolwari-hand-painted-teapot"),
    specifications: [["Material", "Ceramic"], ["Capacity", "750 ml"], ["Finish", "Hand-Painted, Glazed"], ["Care", "Hand wash only"]],
  },
  {
    name: "Indigo Heritage Teapot",
    slug: "indigo-heritage-teapot",
    code: "AC-TS-004",
    category: "Tea Sets & Teapots",
    price: 1899,
    mrp: 2299,
    stock: 14,
    isFeatured: false,
    description: "A tall, classically shaped teapot in rich indigo blue — striking on a tea table or display shelf.",
    image: img("indigo-heritage-teapot"),
    specifications: [["Material", "Ceramic"], ["Capacity", "1 litre"], ["Finish", "Indigo Glaze"], ["Care", "Hand wash only"]],
  },
  {
    name: "Ivory Relief Teapot",
    slug: "ivory-relief-teapot",
    code: "AC-TS-005",
    category: "Tea Sets & Teapots",
    price: 1599,
    mrp: 1899,
    stock: 16,
    isFeatured: false,
    description: "Raised scrollwork and blue floral accents on an ivory teapot standing on small scrolled feet.",
    image: img("ivory-relief-teapot"),
    specifications: [["Material", "Ceramic"], ["Capacity", "700 ml"], ["Finish", "Ivory with Relief Work"], ["Care", "Hand wash only"]],
  },

  // ----------------------------------------------------------------------- Bowls
  {
    name: "Neel Kamal Rice Bowl Set",
    slug: "neel-kamal-rice-bowl-set",
    code: "AC-BW-002",
    category: "Bowls",
    price: 899,
    mrp: 1099,
    stock: 40,
    isFeatured: false,
    description: "Flared bowls with bold blue brushwork on white — the classic blue-and-white look for rice, dal and curd.",
    image: img("neel-kamal-rice-bowl-set"),
    specifications: [["Material", "Ceramic"], ["Capacity", "350 ml each"], ["Pieces", "Set of 4"], ["Finish", "Blue & White"], ["Microwave Safe", "Yes"]],
  },
  {
    name: "Celadon Serving Bowl",
    slug: "celadon-serving-bowl",
    code: "AC-BW-003",
    category: "Bowls",
    price: 999,
    mrp: 1199,
    stock: 22,
    isFeatured: false,
    description: "A wide, shallow serving bowl in a translucent green celadon glaze for salads, fruit and noodles.",
    image: img("celadon-serving-bowl"),
    specifications: [["Material", "Stoneware"], ["Diameter", "24 cm"], ["Finish", "Celadon Glaze"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Floral Scalloped Bowl",
    slug: "floral-scalloped-bowl",
    code: "AC-BW-004",
    category: "Bowls",
    price: 749,
    mrp: 899,
    stock: 28,
    isFeatured: false,
    description: "A lobed white bowl with delicate painted flowers — lovely for desserts, sweets or as a centrepiece.",
    image: img("floral-scalloped-bowl"),
    specifications: [["Material", "Porcelain"], ["Diameter", "18 cm"], ["Finish", "Hand-Painted"], ["Care", "Hand wash recommended"]],
  },
  {
    name: "Large White Salad Bowl",
    slug: "large-white-salad-bowl",
    code: "AC-BW-005",
    category: "Bowls",
    price: 699,
    mrp: 849,
    stock: 35,
    isFeatured: false,
    description: "A roomy, slightly squared white bowl for tossing and serving salads at the table.",
    image: img("large-white-salad-bowl"),
    specifications: [["Material", "Ceramic"], ["Capacity", "1.8 litres"], ["Finish", "Glossy White"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Ivory Soup Bowl Set",
    slug: "ivory-soup-bowl-set",
    code: "AC-BW-006",
    category: "Bowls",
    price: 1199,
    mrp: 1499,
    stock: 30,
    isFeatured: false,
    description: "Six deep ivory bowls with a gentle flare — ideal for soups, ramen and khichdi.",
    image: img("ivory-soup-bowl-set"),
    specifications: [["Material", "Ceramic"], ["Capacity", "500 ml each"], ["Pieces", "Set of 6"], ["Finish", "Ivory Glaze"], ["Microwave Safe", "Yes"]],
  },
  {
    name: "Matte Black Bowl Set",
    slug: "matte-black-bowl-set",
    code: "AC-BW-007",
    category: "Bowls",
    price: 1099,
    mrp: 1349,
    stock: 26,
    isFeatured: false,
    description: "Nesting bowls in a contemporary matte black finish that makes food colours pop.",
    image: img("matte-black-bowl-set"),
    specifications: [["Material", "Stoneware"], ["Pieces", "Set of 4"], ["Finish", "Matte Black"], ["Dishwasher Safe", "Yes"]],
  },

  // ---------------------------------------------------------------------- Plates
  {
    name: "Blue Mosaic Dinner Plate Set",
    slug: "blue-mosaic-dinner-plate-set",
    code: "AC-PL-002",
    category: "Plates",
    price: 1149,
    mrp: 1399,
    stock: 30,
    isFeatured: true,
    description: "Intricate blue mosaic patterns on white — a festive plate for everyday meals and celebrations.",
    image: img("blue-mosaic-dinner-plate-set"),
    specifications: [["Material", "Ceramic"], ["Diameter", "27 cm"], ["Pieces", "Set of 2"], ["Finish", "Printed & Glazed"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Celadon Quarter Plate Set",
    slug: "celadon-quarter-plate-set",
    code: "AC-PL-003",
    category: "Plates",
    price: 1299,
    mrp: 1599,
    stock: 24,
    isFeatured: false,
    description: "Fluted-edge quarter plates in a jade-green celadon glaze for snacks, sides and desserts.",
    image: img("celadon-quarter-plate-set"),
    specifications: [["Material", "Stoneware"], ["Diameter", "20 cm"], ["Pieces", "Set of 6"], ["Finish", "Celadon Glaze"]],
  },
  {
    name: "Floral Dessert Plate Set",
    slug: "floral-dessert-plate-set",
    code: "AC-PL-004",
    category: "Plates",
    price: 999,
    mrp: 1199,
    stock: 28,
    isFeatured: false,
    description: "Scattered garden flowers painted on white dessert plates — made for cake, mithai and tea-time treats.",
    image: img("floral-dessert-plate-set"),
    specifications: [["Material", "Porcelain"], ["Diameter", "19 cm"], ["Pieces", "Set of 4"], ["Finish", "Hand-Painted"]],
  },
  {
    name: "Cream Scalloped Dinner Plate Set",
    slug: "cream-scalloped-dinner-plate-set",
    code: "AC-PL-005",
    category: "Plates",
    price: 1499,
    mrp: 1799,
    stock: 20,
    isFeatured: false,
    description: "Cream plates with a moulded scalloped rim for an elegant, vintage-style table.",
    image: img("cream-scalloped-dinner-plate-set"),
    specifications: [["Material", "Ceramic"], ["Diameter", "26 cm"], ["Pieces", "Set of 6"], ["Finish", "Cream Glaze"], ["Dishwasher Safe", "Yes"]],
  },

  // ----------------------------------------------------------- Decorative Plates
  {
    name: "Shahi Neel Decorative Plate",
    slug: "shahi-neel-decorative-plate",
    code: "AC-DP-001",
    category: "Decorative Plates",
    price: 1690,
    mrp: 1990,
    stock: 10,
    isFeatured: true,
    description: "A cobalt-blue centre framed by a white filigree border — a statement plate for walls and display cabinets.",
    image: img("shahi-neel-decorative-plate"),
    specifications: [["Material", "Ceramic"], ["Diameter", "26 cm"], ["Finish", "Hand-Painted, Glazed"], ["Usage", "Décor / Wall Display"]],
  },
  {
    name: "Guldasta Decorative Plate",
    slug: "guldasta-decorative-plate",
    code: "AC-DP-002",
    category: "Decorative Plates",
    price: 1490,
    mrp: 1790,
    stock: 10,
    isFeatured: false,
    description: "A painted bouquet at the centre with a gilded rim — a thoughtful housewarming gift.",
    image: img("guldasta-decorative-plate"),
    specifications: [["Material", "Porcelain"], ["Diameter", "23 cm"], ["Finish", "Hand-Painted with Gold Rim"], ["Usage", "Décor / Gifting"]],
  },
  {
    name: "Rose Garden Decorative Plate",
    slug: "rose-garden-decorative-plate",
    code: "AC-DP-003",
    category: "Decorative Plates",
    price: 1590,
    mrp: 1890,
    stock: 8,
    isFeatured: false,
    description: "Tiny painted roses across a white field with a patterned border in lilac and gold.",
    image: img("rose-garden-decorative-plate"),
    specifications: [["Material", "Porcelain"], ["Diameter", "24 cm"], ["Finish", "Hand-Painted"], ["Usage", "Décor / Wall Display"]],
  },
  {
    name: "Mandala Medallion Plate",
    slug: "mandala-medallion-plate",
    code: "AC-DP-004",
    category: "Decorative Plates",
    price: 1890,
    mrp: 2190,
    stock: 8,
    isFeatured: false,
    description: "A blue floral medallion surrounded by fine dotted brushwork in earthy tones — symmetry and craft in one piece.",
    image: img("mandala-medallion-plate"),
    specifications: [["Material", "Ceramic"], ["Diameter", "28 cm"], ["Finish", "Hand-Painted, Glazed"], ["Usage", "Décor / Wall Display"]],
  },
  {
    name: "Berry Vine Decorative Plate",
    slug: "berry-vine-decorative-plate",
    code: "AC-DP-005",
    category: "Decorative Plates",
    price: 1390,
    mrp: 1690,
    stock: 10,
    isFeatured: false,
    description: "Trailing vines and berries painted in terracotta and green around a clean white centre.",
    image: img("berry-vine-decorative-plate"),
    specifications: [["Material", "Ceramic"], ["Diameter", "23 cm"], ["Finish", "Hand-Painted"], ["Usage", "Décor / Serving"]],
  },

  // ---------------------------------------------------------------- Serving Ware
  {
    name: "Blue Willow Lidded Tureen",
    slug: "blue-willow-lidded-tureen",
    code: "AC-SW-002",
    category: "Serving Ware",
    price: 2299,
    mrp: 2799,
    stock: 10,
    isFeatured: true,
    description: "A generous lidded tureen with blue pastoral scenes — serve biryani, curries and soups in style.",
    image: img("blue-willow-lidded-tureen"),
    specifications: [["Material", "Ceramic"], ["Capacity", "2.5 litres"], ["Finish", "Blue & White Print"], ["Care", "Hand wash recommended"]],
  },
  {
    name: "Octagonal Serving Platter",
    slug: "octagonal-serving-platter",
    code: "AC-SW-003",
    category: "Serving Ware",
    price: 1199,
    mrp: 1499,
    stock: 18,
    isFeatured: false,
    description: "An eight-sided white platter with a subtly textured rim for starters, kebabs and cheese.",
    image: img("octagonal-serving-platter"),
    specifications: [["Material", "Ceramic"], ["Size", "35 × 25 cm"], ["Finish", "Glossy White"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Embossed Oval Platter",
    slug: "embossed-oval-platter",
    code: "AC-SW-004",
    category: "Serving Ware",
    price: 1399,
    mrp: 1699,
    stock: 15,
    isFeatured: false,
    description: "An oval platter with a raised embossed border — elegant enough for festive spreads.",
    image: img("embossed-oval-platter"),
    specifications: [["Material", "Ceramic"], ["Size", "32 × 24 cm"], ["Finish", "White Embossed"], ["Care", "Hand wash recommended"]],
  },
  {
    name: "Neel Phool Pitcher",
    slug: "neel-phool-pitcher",
    code: "AC-SW-005",
    category: "Serving Ware",
    price: 1099,
    mrp: 1349,
    stock: 18,
    isFeatured: false,
    description: "A curvy pitcher covered in blue flowers — for water, lassi, nimbu paani or a bunch of fresh blooms.",
    image: img("neel-phool-pitcher"),
    specifications: [["Material", "Ceramic"], ["Capacity", "1 litre"], ["Finish", "Blue & White, Hand-Painted"], ["Care", "Hand wash only"]],
  },
  {
    name: "Indigo Stripe Pourer",
    slug: "indigo-stripe-pourer",
    code: "AC-SW-006",
    category: "Serving Ware",
    price: 899,
    mrp: 1099,
    stock: 20,
    isFeatured: false,
    description: "Bold indigo stripes on a rounded white pourer with a loop handle — a cheerful table accent.",
    image: img("indigo-stripe-pourer"),
    specifications: [["Material", "Ceramic"], ["Capacity", "600 ml"], ["Finish", "Hand-Painted Stripes"], ["Care", "Hand wash only"]],
  },
  {
    name: "White Leaf Serving Platter",
    slug: "white-leaf-serving-platter",
    code: "AC-SW-007",
    category: "Serving Ware",
    price: 999,
    mrp: 1199,
    stock: 20,
    isFeatured: false,
    description: "Embossed leaf patterns on an all-white round platter — great for fruit, dry fruits and desserts.",
    image: img("white-leaf-serving-platter"),
    specifications: [["Material", "Ceramic"], ["Diameter", "30 cm"], ["Finish", "White Embossed"], ["Dishwasher Safe", "Yes"]],
  },

  // -------------------------------------------------------------- Jars & Storage
  {
    name: "Blue & White Kitchen Jar Set",
    slug: "blue-white-kitchen-jar-set",
    code: "AC-JS-001",
    category: "Jars & Storage",
    price: 1499,
    mrp: 1799,
    stock: 20,
    isFeatured: true,
    description: "Lidded jars with blue geometric patterns — perfect as achaar (pickle) jars or for spices, tea and sugar.",
    image: img("blue-white-kitchen-jar-set"),
    specifications: [["Material", "Ceramic"], ["Capacity", "500 ml, 750 ml, 1 litre"], ["Pieces", "Set of 3 with Lids"], ["Finish", "Blue & White, Glazed"], ["Food Safe", "Yes"]],
  },
  {
    name: "Rose Garden Lidded Canister",
    slug: "rose-garden-lidded-canister",
    code: "AC-JS-002",
    category: "Jars & Storage",
    price: 1299,
    mrp: 1599,
    stock: 14,
    isFeatured: false,
    description: "A painted canister with pink roses and a mint-green band — store cookies, tea or sweets beautifully.",
    image: img("rose-garden-lidded-canister"),
    specifications: [["Material", "Porcelain"], ["Capacity", "900 ml"], ["Finish", "Hand-Painted"], ["Food Safe", "Yes"]],
  },
  {
    name: "Heritage Painted Tea Canister",
    slug: "heritage-painted-tea-canister",
    code: "AC-JS-003",
    category: "Jars & Storage",
    price: 1199,
    mrp: 1449,
    stock: 12,
    isFeatured: false,
    description: "A square tea caddy decorated with red, blue and green floral panels and a snug lid.",
    image: img("heritage-painted-tea-canister"),
    specifications: [["Material", "Ceramic"], ["Capacity", "600 ml"], ["Finish", "Hand-Painted, Glazed"], ["Usage", "Tea / Spice Storage"]],
  },

  // ------------------------------------------------------------- Planters & Pots
  {
    name: "Buddha Face Planter",
    slug: "buddha-face-planter",
    code: "AC-PP-001",
    category: "Planters & Pots",
    price: 899,
    mrp: 1099,
    stock: 25,
    isFeatured: true,
    description: "A serene Buddha head planter in white glaze — plant a snake plant or succulent for a calm corner.",
    image: img("buddha-face-planter"),
    specifications: [["Material", "Ceramic"], ["Size", "6 inch"], ["Drainage Hole", "Yes"], ["Finish", "Glossy White"], ["Usage", "Indoor"]],
  },
  {
    name: "Owl Planter",
    slug: "owl-planter",
    code: "AC-PP-002",
    category: "Planters & Pots",
    price: 599,
    mrp: 749,
    stock: 30,
    isFeatured: false,
    description: "A playful grey owl planter for succulents and small herbs on desks and windowsills.",
    image: img("owl-planter"),
    specifications: [["Material", "Ceramic"], ["Size", "5 inch"], ["Drainage Hole", "Yes"], ["Finish", "Grey Glaze"], ["Usage", "Indoor"]],
  },
  {
    name: "Ribbed Pastel Planter Set",
    slug: "ribbed-pastel-planter-set",
    code: "AC-PP-003",
    category: "Planters & Pots",
    price: 1999,
    mrp: 2399,
    stock: 12,
    isFeatured: false,
    description: "Three ribbed planters in butter yellow, sky blue and ivory — stack them or group them on a balcony.",
    image: img("ribbed-pastel-planter-set"),
    specifications: [["Material", "Ceramic"], ["Sizes", "6, 8 and 10 inch"], ["Pieces", "Set of 3"], ["Drainage Hole", "Yes"], ["Usage", "Indoor / Balcony"]],
  },
  {
    name: "Bamboo Stripe Planter",
    slug: "bamboo-stripe-planter",
    code: "AC-PP-004",
    category: "Planters & Pots",
    price: 799,
    mrp: 949,
    stock: 18,
    isFeatured: false,
    description: "A bamboo-inspired planter with green and white stripes and a scalloped rim.",
    image: img("bamboo-stripe-planter"),
    specifications: [["Material", "Ceramic"], ["Size", "7 inch"], ["Drainage Hole", "Yes"], ["Finish", "Glazed Green & White"]],
  },
  {
    name: "White Orb Planter",
    slug: "white-orb-planter",
    code: "AC-PP-005",
    category: "Planters & Pots",
    price: 449,
    mrp: 549,
    stock: 40,
    isFeatured: false,
    description: "A textured white sphere planter — ideal for anthuriums, pothos cuttings and air plants.",
    image: img("white-orb-planter"),
    specifications: [["Material", "Ceramic"], ["Size", "4 inch"], ["Finish", "Textured White"], ["Usage", "Tabletop"]],
  },
  {
    name: "Square Succulent Planter",
    slug: "square-succulent-planter",
    code: "AC-PP-006",
    category: "Planters & Pots",
    price: 399,
    mrp: 499,
    stock: 45,
    isFeatured: false,
    description: "A compact square planter with a weathered white finish for succulents and seedlings.",
    image: img("square-succulent-planter"),
    specifications: [["Material", "Ceramic"], ["Size", "4 inch"], ["Drainage Hole", "Yes"], ["Finish", "Antique White"]],
  },
  {
    name: "Classic White Round Planter",
    slug: "classic-white-round-planter",
    code: "AC-PP-007",
    category: "Planters & Pots",
    price: 549,
    mrp: 699,
    stock: 35,
    isFeatured: false,
    description: "A timeless round white planter that suits every plant and every room.",
    image: img("classic-white-round-planter"),
    specifications: [["Material", "Ceramic"], ["Size", "6 inch"], ["Drainage Hole", "Yes"], ["Finish", "Glossy White"], ["Usage", "Indoor"]],
  },

  // --------------------------------------------------------------- Vases & Décor
  {
    name: "Twin Bud Vases",
    slug: "twin-bud-vases",
    code: "AC-VD-001",
    category: "Vases & Décor",
    price: 799,
    mrp: 999,
    stock: 25,
    isFeatured: false,
    description: "A pair of slim white bud vases for single stems and dried branches.",
    image: img("twin-bud-vases"),
    specifications: [["Material", "Ceramic"], ["Height", "18 cm and 15 cm"], ["Pieces", "Set of 2"], ["Finish", "Matte White"]],
  },
  {
    name: "Celadon Bottle Vase",
    slug: "celadon-bottle-vase",
    code: "AC-VD-002",
    category: "Vases & Décor",
    price: 1199,
    mrp: 1449,
    stock: 16,
    isFeatured: false,
    description: "A narrow-neck bottle vase in soft celadon — beautiful alone or grouped in different heights.",
    image: img("celadon-bottle-vase"),
    specifications: [["Material", "Stoneware"], ["Height", "22 cm"], ["Finish", "Celadon Glaze"], ["Usage", "Flowers / Décor"]],
  },
  {
    name: "Indigo Ombre Bottle Vase",
    slug: "indigo-ombre-vase",
    code: "AC-VD-003",
    category: "Vases & Décor",
    price: 1499,
    mrp: 1799,
    stock: 10,
    isFeatured: false,
    description: "A glossy bottle vase that fades from deep indigo to white, finished with a decorative metal stopper.",
    image: img("indigo-ombre-vase"),
    specifications: [["Material", "Ceramic"], ["Height", "30 cm"], ["Finish", "Ombre Glaze"], ["Usage", "Décor"]],
  },
  {
    name: "Blush Pink Bud Vase",
    slug: "blush-pink-bud-vase",
    code: "AC-VD-004",
    category: "Vases & Décor",
    price: 549,
    mrp: 699,
    stock: 30,
    isFeatured: false,
    description: "A petite blush-pink vase with a rounded belly — made for a single rose or a few sprigs.",
    image: img("blush-pink-bud-vase"),
    specifications: [["Material", "Ceramic"], ["Height", "12 cm"], ["Finish", "Glossy Blush"], ["Usage", "Tabletop"]],
  },
];
