// Second catalogue expansion, following the Khurja range more closely:
// oil/container bottles, jugs and ewers, kulhads, hanging/bonsai/outdoor
// pots and bottle vases. Copy and prices are our own; photos are CC0 —
// see public/products/CREDITS.md. No ratings: those come from real reviews.
import type { SeedProduct } from "./catalog";

const img = (slug: string) => `/products/${slug}.jpg`;

export const khurjaCategoryDescriptions: Record<string, string> = {
  "Bottles & Dispensers":
    "Glazed oil dispensers and container bottles — the everyday classics of Khurja kitchens.",
};

export const khurjaRangeProducts: SeedProduct[] = [
  // ------------------------------------------------------ Bottles & Dispensers
  {
    name: "Drip Glaze Oil Dispenser",
    slug: "drip-glaze-oil-dispenser",
    code: "AC-BD-001",
    category: "Bottles & Dispensers",
    price: 649,
    mrp: 799,
    stock: 30,
    isFeatured: true,
    description: "An ivory oil dispenser with flowing brown drip glaze and a metal pour-stopper — pretty enough to leave out beside the stove.",
    image: img("drip-glaze-oil-dispenser"),
    specifications: [["Material", "Ceramic"], ["Capacity", "500 ml"], ["Finish", "Drip Glaze"], ["Stopper", "Metal pourer"], ["Food Safe", "Yes"]],
  },
  {
    name: "Rustic Stoneware Bottle Trio",
    slug: "rustic-stoneware-bottle-trio",
    code: "AC-BD-002",
    category: "Bottles & Dispensers",
    price: 899,
    mrp: 1099,
    stock: 20,
    isFeatured: false,
    description: "Three square-shouldered stoneware bottles with sand-toned glaze and red-tipped necks, for oil, vinegar or water.",
    image: img("rustic-stoneware-bottle-trio"),
    specifications: [["Material", "Stoneware"], ["Capacity", "400 ml each"], ["Pieces", "Set of 3"], ["Finish", "Matte Sand Glaze"]],
  },
  {
    name: "Celadon Brushstroke Oil Jar",
    slug: "celadon-brushstroke-oil-jar",
    code: "AC-BD-003",
    category: "Bottles & Dispensers",
    price: 549,
    mrp: 699,
    stock: 25,
    isFeatured: false,
    description: "A squat, low-spilling oil jar in sage celadon with loose black brushstrokes — steady on any counter.",
    image: img("celadon-brushstroke-oil-jar"),
    specifications: [["Material", "Stoneware"], ["Capacity", "350 ml"], ["Finish", "Celadon with Brushwork"], ["Food Safe", "Yes"]],
  },
  {
    name: "Oxblood Glaze Bottle",
    slug: "oxblood-glaze-bottle",
    code: "AC-BD-004",
    category: "Bottles & Dispensers",
    price: 799,
    mrp: 999,
    stock: 15,
    isFeatured: false,
    description: "A long-necked bottle in deep oxblood red — use it for water at the table or as a single-stem vase.",
    image: img("oxblood-glaze-bottle"),
    specifications: [["Material", "Ceramic"], ["Height", "28 cm"], ["Finish", "Oxblood Glaze"], ["Usage", "Water / Décor"]],
  },
  {
    name: "Earthen Glaze Bottle",
    slug: "earthen-glaze-bottle",
    code: "AC-BD-005",
    category: "Bottles & Dispensers",
    price: 699,
    mrp: 849,
    stock: 18,
    isFeatured: false,
    description: "A pear-shaped bottle with a warm brown glaze that pools darker at the base.",
    image: img("earthen-glaze-bottle"),
    specifications: [["Material", "Ceramic"], ["Height", "26 cm"], ["Finish", "Earthen Brown Glaze"], ["Usage", "Water / Décor"]],
  },

  // ------------------------------------------------------------- Serving Ware
  {
    name: "Classic White Pitcher",
    slug: "classic-white-pitcher",
    code: "AC-SW-008",
    category: "Serving Ware",
    price: 799,
    mrp: 999,
    stock: 25,
    isFeatured: false,
    description: "A tall white pitcher with a generous handle — for water, buttermilk or a bunch of fresh flowers.",
    image: img("classic-white-pitcher"),
    specifications: [["Material", "Ceramic"], ["Capacity", "1.2 litres"], ["Finish", "Glossy White"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Neelam Hand-Painted Jug",
    slug: "neelam-hand-painted-jug",
    code: "AC-SW-009",
    category: "Serving Ware",
    price: 1290,
    mrp: 1590,
    stock: 12,
    isFeatured: true,
    description: "Bold cobalt leaves and a green band painted by hand on a tall white jug — classic Khurja colours.",
    image: img("neelam-hand-painted-jug"),
    specifications: [["Material", "Ceramic"], ["Capacity", "1 litre"], ["Finish", "Hand-Painted, Glazed"], ["Care", "Hand wash only"]],
  },
  {
    name: "Blue Salt-Glaze Jug",
    slug: "blue-salt-glaze-jug",
    code: "AC-SW-010",
    category: "Serving Ware",
    price: 1490,
    mrp: 1790,
    stock: 8,
    isFeatured: false,
    description: "A grey and cobalt stoneware jug with moulded bands of relief — a collector-style serving piece.",
    image: img("blue-salt-glaze-jug"),
    specifications: [["Material", "Stoneware"], ["Capacity", "1 litre"], ["Finish", "Salt Glaze, Relief Work"], ["Care", "Hand wash only"]],
  },
  {
    name: "Tulip Lidded Jug",
    slug: "tulip-lidded-jug",
    code: "AC-SW-011",
    category: "Serving Ware",
    price: 1390,
    mrp: 1690,
    stock: 10,
    isFeatured: false,
    description: "Blue and yellow tulips painted on a round-bellied jug, finished with a hinged metal lid.",
    image: img("tulip-lidded-jug"),
    specifications: [["Material", "Ceramic"], ["Capacity", "900 ml"], ["Finish", "Hand-Painted"], ["Lid", "Hinged metal"]],
  },
  {
    name: "Floral Gravy Boat",
    slug: "floral-gravy-boat",
    code: "AC-SW-012",
    category: "Serving Ware",
    price: 749,
    mrp: 899,
    stock: 20,
    isFeatured: false,
    description: "A scalloped gravy boat with painted flowers and vines — for curries, chutneys and sauces.",
    image: img("floral-gravy-boat"),
    specifications: [["Material", "Ceramic"], ["Capacity", "400 ml"], ["Finish", "Hand-Painted"], ["Care", "Hand wash recommended"]],
  },
  {
    name: "Silver-Blue Lustre Jug",
    slug: "silver-blue-lustre-jug",
    code: "AC-SW-013",
    category: "Serving Ware",
    price: 1190,
    mrp: 1449,
    stock: 10,
    isFeatured: false,
    description: "A pale blue jug with shimmering silver lustre patterns — an elegant cream or milk jug.",
    image: img("silver-blue-lustre-jug"),
    specifications: [["Material", "Ceramic"], ["Capacity", "600 ml"], ["Finish", "Lustre Glaze"], ["Care", "Hand wash only, not microwave safe"]],
  },
  {
    name: "Calligraphy Ewer",
    slug: "calligraphy-ewer",
    code: "AC-SW-014",
    category: "Serving Ware",
    price: 1590,
    mrp: 1890,
    stock: 8,
    isFeatured: false,
    description: "A white ewer with a long spout and a band of black brush calligraphy — for serving sharbat or as décor.",
    image: img("calligraphy-ewer"),
    specifications: [["Material", "Ceramic"], ["Capacity", "800 ml"], ["Finish", "Hand-Painted"], ["Usage", "Serving / Décor"]],
  },
  {
    name: "Scalloped Serving Tray",
    slug: "scalloped-serving-tray",
    code: "AC-SW-015",
    category: "Serving Ware",
    price: 899,
    mrp: 1099,
    stock: 18,
    isFeatured: false,
    description: "A round white tray with a softly scalloped edge — serve tea, sweets or snacks with a little ceremony.",
    image: img("scalloped-serving-tray"),
    specifications: [["Material", "Ceramic"], ["Diameter", "30 cm"], ["Finish", "Glossy White"], ["Dishwasher Safe", "Yes"]],
  },
  {
    name: "Floral Handled Dish",
    slug: "floral-handled-dish",
    code: "AC-SW-016",
    category: "Serving Ware",
    price: 1190,
    mrp: 1449,
    stock: 12,
    isFeatured: false,
    description: "A shaped dish with twin handles, a painted thistle bouquet and a gilded border.",
    image: img("floral-handled-dish"),
    specifications: [["Material", "Porcelain"], ["Size", "26 × 22 cm"], ["Finish", "Hand-Painted with Gold"], ["Care", "Hand wash only"]],
  },

  // -------------------------------------------------------------------- Bowls
  {
    name: "Terracotta Footed Bowl",
    slug: "terracotta-footed-bowl",
    code: "AC-BW-008",
    category: "Bowls",
    price: 649,
    mrp: 799,
    stock: 20,
    isFeatured: false,
    description: "A deep terracotta-red bowl on a short foot with a glazed interior — great for fruit, salads or serving dal.",
    image: img("terracotta-footed-bowl"),
    specifications: [["Material", "Terracotta, Glazed Inside"], ["Diameter", "20 cm"], ["Finish", "Earthen Red"], ["Care", "Hand wash only"]],
  },
  {
    name: "Kali Phool Bowl",
    slug: "kali-phool-bowl",
    code: "AC-BW-009",
    category: "Bowls",
    price: 799,
    mrp: 949,
    stock: 15,
    isFeatured: false,
    description: "Black floral sgraffito on a white body — a striking bowl for the table or a display shelf.",
    image: img("kali-phool-bowl"),
    specifications: [["Material", "Stoneware"], ["Diameter", "16 cm"], ["Finish", "Black & White Sgraffito"], ["Care", "Hand wash only"]],
  },

  // -------------------------------------------------------------- Cups & Mugs
  {
    name: "Kulhad Chai Cup Set",
    slug: "kulhad-chai-cup-set",
    code: "AC-CM-010",
    category: "Cups & Mugs",
    price: 399,
    mrp: 499,
    stock: 60,
    isFeatured: true,
    description: "Traditional clay kulhads that give chai its earthy aroma — reusable, glazed inside for easy washing.",
    image: img("kulhad-chai-cup-set"),
    specifications: [["Material", "Terracotta, Glazed Inside"], ["Capacity", "150 ml each"], ["Pieces", "Set of 6"], ["Care", "Hand wash only"]],
  },
  {
    name: "Mini Kulhad Set",
    slug: "mini-kulhad-set",
    code: "AC-CM-011",
    category: "Cups & Mugs",
    price: 449,
    mrp: 549,
    stock: 50,
    isFeatured: false,
    description: "Small kulhads for shots of chai, kulfi, phirni or rabri — perfect for parties and festive thalis.",
    image: img("mini-kulhad-set"),
    specifications: [["Material", "Terracotta"], ["Capacity", "60 ml each"], ["Pieces", "Set of 12"], ["Care", "Hand wash only"]],
  },

  // ------------------------------------------------------ Tea Sets & Teapots
  {
    name: "Floral Tea Service",
    slug: "floral-tea-service",
    code: "AC-TS-006",
    category: "Tea Sets & Teapots",
    price: 2890,
    mrp: 3490,
    stock: 8,
    isFeatured: false,
    description: "A lidded sugar pot with cups and saucers painted with soft landscapes and gilded rims.",
    image: img("floral-tea-service"),
    specifications: [["Material", "Porcelain"], ["Pieces", "Sugar Pot + 4 Cups + 4 Saucers"], ["Finish", "Hand-Painted with Gold Rim"], ["Care", "Hand wash only"]],
  },
  {
    name: "Fuchsia Tea Set",
    slug: "fuchsia-tea-set",
    code: "AC-TS-007",
    category: "Tea Sets & Teapots",
    price: 3290,
    mrp: 3990,
    stock: 6,
    isFeatured: true,
    description: "Teapot, sugar pot, cups and saucers painted with trailing pink fuchsias — a complete set for tea parties.",
    image: img("fuchsia-tea-set"),
    specifications: [["Material", "Porcelain"], ["Pieces", "Teapot + Sugar Pot + 4 Cups + 4 Saucers"], ["Finish", "Hand-Painted"], ["Care", "Hand wash only"]],
  },

  // -------------------------------------------------------------- Dinner Sets
  {
    name: "Slate Grey Dinner Set",
    slug: "slate-grey-dinner-set",
    code: "AC-DS-002",
    category: "Dinner Sets",
    price: 4490,
    mrp: 5490,
    stock: 10,
    isFeatured: true,
    description: "Layered plates in charcoal and dove grey with matching bowls — a modern, restaurant-style table setting.",
    image: img("slate-grey-dinner-set"),
    specifications: [["Material", "Stoneware"], ["Pieces", "18 Pieces (serves 6)"], ["Finish", "Matte Grey"], ["Microwave Safe", "Yes"], ["Dishwasher Safe", "Yes"]],
  },

  // ----------------------------------------------------------- Jars & Storage
  {
    name: "Blue Phoenix Canister",
    slug: "blue-phoenix-canister",
    code: "AC-JS-004",
    category: "Jars & Storage",
    price: 1190,
    mrp: 1449,
    stock: 12,
    isFeatured: false,
    description: "A cylindrical blue-and-white container with a phoenix and cloud pattern — for utensils, brushes or dry snacks.",
    image: img("blue-phoenix-canister"),
    specifications: [["Material", "Porcelain"], ["Height", "14 cm"], ["Finish", "Blue & White"], ["Usage", "Storage / Utensil Holder"]],
  },
  {
    name: "Grey Vine Lidded Jar",
    slug: "grey-vine-lidded-jar",
    code: "AC-JS-005",
    category: "Jars & Storage",
    price: 1290,
    mrp: 1590,
    stock: 10,
    isFeatured: false,
    description: "A lidded jar with white grapevines in relief on dove grey — ideal for sugar, tea or dry fruits.",
    image: img("grey-vine-lidded-jar"),
    specifications: [["Material", "Ceramic"], ["Capacity", "1 litre"], ["Finish", "Relief Work"], ["Food Safe", "Yes"]],
  },
  {
    name: "Salt & Pepper Shaker Set",
    slug: "salt-pepper-shaker-set",
    code: "AC-JS-006",
    category: "Jars & Storage",
    price: 449,
    mrp: 549,
    stock: 40,
    isFeatured: false,
    description: "A pair of labelled white shakers with steel tops — a clean, classic touch for the dining table.",
    image: img("salt-pepper-shaker-set"),
    specifications: [["Material", "Ceramic"], ["Pieces", "Set of 2"], ["Lids", "Stainless steel"], ["Finish", "Glossy White"]],
  },
  {
    name: "Amber Glaze Butter Dish",
    slug: "amber-glaze-butter-dish",
    code: "AC-JS-007",
    category: "Jars & Storage",
    price: 899,
    mrp: 1099,
    stock: 15,
    isFeatured: false,
    description: "A domed butter dish in a rich amber glaze with a finial lid — keeps butter or ghee covered at the table.",
    image: img("amber-glaze-butter-dish"),
    specifications: [["Material", "Ceramic"], ["Size", "18 cm"], ["Finish", "Amber Glaze"], ["Food Safe", "Yes"]],
  },

  // ---------------------------------------------------------- Planters & Pots
  {
    name: "Teal Hanging Planter",
    slug: "teal-hanging-planter",
    code: "AC-PP-008",
    category: "Planters & Pots",
    price: 849,
    mrp: 999,
    stock: 20,
    isFeatured: false,
    description: "A wide teal bowl planter with hanging ropes — lovely for trailing plants on a verandah.",
    image: img("teal-hanging-planter"),
    specifications: [["Material", "Ceramic"], ["Size", "10 inch"], ["Includes", "Hanging ropes"], ["Drainage Hole", "Yes"]],
  },
  {
    name: "White Hanging Planter",
    slug: "white-hanging-planter",
    code: "AC-PP-009",
    category: "Planters & Pots",
    price: 699,
    mrp: 849,
    stock: 25,
    isFeatured: false,
    description: "A ribbed white hanging pot for petunias, ferns and money plants.",
    image: img("white-hanging-planter"),
    specifications: [["Material", "Ceramic"], ["Size", "7 inch"], ["Includes", "Hanging chain"], ["Drainage Hole", "Yes"]],
  },
  {
    name: "Terracotta Hanging Planter",
    slug: "terracotta-hanging-planter",
    code: "AC-PP-010",
    category: "Planters & Pots",
    price: 599,
    mrp: 749,
    stock: 25,
    isFeatured: false,
    description: "A classic terracotta hanging bowl — breathable clay keeps succulents and trailing plants healthy.",
    image: img("terracotta-hanging-planter"),
    specifications: [["Material", "Terracotta"], ["Size", "8 inch"], ["Includes", "Hanging wires"], ["Drainage Hole", "Yes"]],
  },
  {
    name: "Wall-Mount Planter Pair",
    slug: "wall-mount-planter-pair",
    code: "AC-PP-011",
    category: "Planters & Pots",
    price: 999,
    mrp: 1199,
    stock: 18,
    isFeatured: false,
    description: "Two clean white wall planters for a living green wall of pothos, ferns or herbs.",
    image: img("wall-mount-planter-pair"),
    specifications: [["Material", "Ceramic"], ["Size", "8 inch each"], ["Pieces", "Set of 2"], ["Mounting", "Screws included"]],
  },
  {
    name: "Turquoise Bonsai Pot",
    slug: "turquoise-bonsai-pot",
    code: "AC-PP-012",
    category: "Planters & Pots",
    price: 1190,
    mrp: 1449,
    stock: 10,
    isFeatured: true,
    description: "A square bonsai pot with a crackled turquoise glaze and small feet for drainage and airflow.",
    image: img("turquoise-bonsai-pot"),
    specifications: [["Material", "Stoneware"], ["Size", "8 inch"], ["Drainage Holes", "Yes, with feet"], ["Finish", "Crackle Turquoise"], ["Usage", "Bonsai"]],
  },
  {
    name: "Cylinder Succulent Pot Pair",
    slug: "cylinder-succulent-pot-pair",
    code: "AC-PP-013",
    category: "Planters & Pots",
    price: 599,
    mrp: 749,
    stock: 30,
    isFeatured: false,
    description: "A white and a speckled grey cylinder pot for succulents and small cacti.",
    image: img("cylinder-succulent-pot-pair"),
    specifications: [["Material", "Ceramic"], ["Size", "3 and 4 inch"], ["Pieces", "Set of 2"], ["Usage", "Succulents / Desk"]],
  },
  {
    name: "Rope Texture Grey Pot",
    slug: "rope-texture-grey-pot",
    code: "AC-PP-014",
    category: "Planters & Pots",
    price: 499,
    mrp: 599,
    stock: 30,
    isFeatured: false,
    description: "A concrete-grey pot with a rope-wrapped texture — understated and modern.",
    image: img("rope-texture-grey-pot"),
    specifications: [["Material", "Ceramic"], ["Size", "5 inch"], ["Finish", "Textured Grey"], ["Drainage Hole", "Yes"]],
  },
  {
    name: "Shallow Succulent Bowl",
    slug: "shallow-succulent-bowl",
    code: "AC-PP-015",
    category: "Planters & Pots",
    price: 549,
    mrp: 699,
    stock: 25,
    isFeatured: false,
    description: "A wide, shallow planter for building a mini succulent garden or terrarium.",
    image: img("shallow-succulent-bowl"),
    specifications: [["Material", "Ceramic"], ["Diameter", "20 cm"], ["Finish", "Matte White"], ["Drainage Hole", "Yes"]],
  },
  {
    name: "Hand-Painted Talavera Pot",
    slug: "hand-painted-talavera-pot",
    code: "AC-PP-016",
    category: "Planters & Pots",
    price: 1290,
    mrp: 1590,
    stock: 12,
    isFeatured: true,
    description: "A bright pot hand-painted with bold florals in red, yellow and blue — a cheerful focal point for the balcony.",
    image: img("hand-painted-talavera-pot"),
    specifications: [["Material", "Ceramic"], ["Size", "8 inch"], ["Finish", "Hand-Painted, Glazed"], ["Drainage Hole", "Yes"], ["Usage", "Indoor / Outdoor"]],
  },
  {
    name: "Cobalt Glazed Outdoor Pot",
    slug: "cobalt-glazed-outdoor-pot",
    code: "AC-PP-017",
    category: "Planters & Pots",
    price: 1890,
    mrp: 2290,
    stock: 10,
    isFeatured: false,
    description: "A large frost-resistant pot in deep cobalt glaze for palms, bamboo and outdoor shrubs.",
    image: img("cobalt-glazed-outdoor-pot"),
    specifications: [["Material", "Stoneware"], ["Size", "14 inch"], ["Finish", "Cobalt Glaze"], ["Drainage Hole", "Yes"], ["Usage", "Outdoor"]],
  },
  {
    name: "Terracotta Pot Set",
    slug: "terracotta-pot-set",
    code: "AC-PP-018",
    category: "Planters & Pots",
    price: 799,
    mrp: 999,
    stock: 30,
    isFeatured: false,
    description: "Six natural terracotta pots in graded sizes — breathable clay for herbs, flowers and seedlings.",
    image: img("terracotta-pot-set"),
    specifications: [["Material", "Terracotta"], ["Sizes", "4 to 8 inch"], ["Pieces", "Set of 6"], ["Drainage Hole", "Yes"]],
  },
  {
    name: "Pastel Mini Planter Set",
    slug: "pastel-mini-planter-set",
    code: "AC-PP-019",
    category: "Planters & Pots",
    price: 699,
    mrp: 849,
    stock: 25,
    isFeatured: false,
    description: "Mini pots with matching saucers in soft blue, lime and cream — for herbs on the kitchen windowsill.",
    image: img("pastel-mini-planter-set"),
    specifications: [["Material", "Ceramic"], ["Size", "4 inch each"], ["Pieces", "Set of 3 with saucers"], ["Drainage Hole", "Yes"]],
  },
  {
    name: "Bright Garden Pot Set",
    slug: "bright-garden-pot-set",
    code: "AC-PP-020",
    category: "Planters & Pots",
    price: 1590,
    mrp: 1890,
    stock: 12,
    isFeatured: false,
    description: "Sunny yellow and turquoise ribbed pots that bring colour to a garden or terrace.",
    image: img("bright-garden-pot-set"),
    specifications: [["Material", "Ceramic"], ["Sizes", "8 and 10 inch"], ["Pieces", "Set of 3"], ["Drainage Hole", "Yes"], ["Usage", "Outdoor"]],
  },

  // ------------------------------------------------------------ Vases & Décor
  {
    name: "Sky Blue Bottle Vase",
    slug: "sky-blue-bottle-vase",
    code: "AC-VD-005",
    category: "Vases & Décor",
    price: 1290,
    mrp: 1590,
    stock: 12,
    isFeatured: false,
    description: "A faceted bottle vase in clear sky-blue glaze — calm, bright and beautiful on its own.",
    image: img("sky-blue-bottle-vase"),
    specifications: [["Material", "Porcelain"], ["Height", "30 cm"], ["Finish", "Sky Blue Glaze"], ["Usage", "Flowers / Décor"]],
  },
  {
    name: "Blue Lotus Bottle Vase",
    slug: "blue-lotus-bottle-vase",
    code: "AC-VD-006",
    category: "Vases & Décor",
    price: 1690,
    mrp: 1990,
    stock: 10,
    isFeatured: true,
    description: "A round-bellied bottle vase covered in cobalt lotus scrolls — the timeless blue-and-white look.",
    image: img("blue-lotus-bottle-vase"),
    specifications: [["Material", "Porcelain"], ["Height", "32 cm"], ["Finish", "Blue & White, Hand-Painted"], ["Usage", "Décor"]],
  },
  {
    name: "Ink Floral Vase",
    slug: "ink-floral-vase",
    code: "AC-VD-007",
    category: "Vases & Décor",
    price: 1490,
    mrp: 1790,
    stock: 10,
    isFeatured: false,
    description: "A high-shouldered vase with pale floral scrolls carved through a deep brown-black glaze.",
    image: img("ink-floral-vase"),
    specifications: [["Material", "Stoneware"], ["Height", "28 cm"], ["Finish", "Sgraffito on Dark Glaze"], ["Usage", "Décor"]],
  },
  {
    name: "White Fluted Vase",
    slug: "white-fluted-vase",
    code: "AC-VD-008",
    category: "Vases & Décor",
    price: 449,
    mrp: 549,
    stock: 35,
    isFeatured: false,
    description: "A small fluted white vase for daisies, jasmine or a single rose on the dining table.",
    image: img("white-fluted-vase"),
    specifications: [["Material", "Ceramic"], ["Height", "14 cm"], ["Finish", "Glossy White"], ["Usage", "Tabletop"]],
  },
  {
    name: "Tall Terracotta Floor Vase",
    slug: "tall-terracotta-floor-vase",
    code: "AC-VD-009",
    category: "Vases & Décor",
    price: 2290,
    mrp: 2790,
    stock: 6,
    isFeatured: false,
    description: "A tall textured terracotta vase for dried pampas, branches or simply to fill an empty corner.",
    image: img("tall-terracotta-floor-vase"),
    specifications: [["Material", "Terracotta"], ["Height", "60 cm"], ["Finish", "Natural Clay"], ["Usage", "Floor Décor"]],
  },
  {
    name: "Gourd Vase Pair",
    slug: "gourd-vase-pair",
    code: "AC-VD-010",
    category: "Vases & Décor",
    price: 1890,
    mrp: 2290,
    stock: 8,
    isFeatured: false,
    description: "Two gourd-shaped vases — one in deep midnight blue, one in textured terracotta.",
    image: img("gourd-vase-pair"),
    specifications: [["Material", "Ceramic"], ["Height", "25 cm"], ["Pieces", "Set of 2"], ["Usage", "Décor"]],
  },

  // -------------------------------------------------------- Decorative Plates
  {
    name: "Gulabi Medallion Plate",
    slug: "gulabi-medallion-plate",
    code: "AC-DP-006",
    category: "Decorative Plates",
    price: 1790,
    mrp: 2090,
    stock: 8,
    isFeatured: false,
    description: "A vivid pink plate with painted medallion panels of flowers and figures — a statement wall piece.",
    image: img("gulabi-medallion-plate"),
    specifications: [["Material", "Porcelain"], ["Diameter", "26 cm"], ["Finish", "Hand-Painted"], ["Usage", "Décor / Wall Display"]],
  },
];
