// Third catalogue expansion: festive diyas and pooja items, clay earthenware,
// café cups, tea bowls, everyday bowls and plates, more decorative plates,
// serveware, planters and vases — the wider Khurja range. Copy and prices are
// our own; photos are CC0 (see public/products/CREDITS.md). No ratings.
import type { SeedProduct } from "./catalog";

const img = (slug: string) => `/products/${slug}.jpg`;

type Spec = [string, string][];
const p = (
  name: string,
  slug: string,
  code: string,
  category: string,
  price: number,
  mrp: number,
  stock: number,
  description: string,
  specifications: Spec,
  isFeatured = false
): SeedProduct => ({ name, slug, code, category, price, mrp, stock, description, specifications, isFeatured, image: img(slug) });

export const khurja2CategoryDescriptions: Record<string, string> = {
  "Diyas & Pooja": "Terracotta and glazed diyas, tealight holders and pooja essentials for festivals and everyday prayer.",
  "Clay & Earthenware": "Traditional matkas, handis and clay tumblers — natural cooling, earthy flavour.",
};

export const khurjaRange2Products: SeedProduct[] = [
  // ------------------------------------------------------------ Diyas & Pooja
  p("Terracotta Diya Set", "terracotta-diya-set", "AC-DY-001", "Diyas & Pooja", 299, 399, 120,
    "Classic hand-shaped terracotta diyas for Diwali, weddings and daily aarti. Pre-soaked clay burns cleaner and lasts longer.",
    [["Material", "Terracotta"], ["Pieces", "Set of 12"], ["Size", "7 cm diameter"], ["Usage", "Oil / Ghee lamp"]], true),
  p("Hand-Painted Festive Diya", "hand-painted-festive-diya", "AC-DY-002", "Diyas & Pooja", 249, 329, 80,
    "A deep terracotta diya painted with white and yellow motifs — bright, festive and ready to gift.",
    [["Material", "Terracotta"], ["Pieces", "Set of 4"], ["Finish", "Hand-Painted"], ["Usage", "Oil / Ghee lamp"]]),
  p("Painted Clay Diya Pair", "painted-clay-diya-pair", "AC-DY-003", "Diyas & Pooja", 349, 449, 60,
    "Two wide-rim diyas with painted borders, sized to burn through a long pooja.",
    [["Material", "Terracotta"], ["Pieces", "Set of 2"], ["Size", "10 cm diameter"], ["Finish", "Hand-Painted"]]),
  p("Diya Thali Set", "diya-thali-set", "AC-DY-004", "Diyas & Pooja", 899, 1099, 30,
    "A decorated pooja thali with a ring of petal-shaped diyas — a ready centrepiece for Diwali and festive rangoli.",
    [["Material", "Terracotta with Metal Thali"], ["Pieces", "Thali + 8 Diyas"], ["Thali Size", "30 cm"], ["Usage", "Pooja / Décor"]], true),
  p("Lotus Tealight Holder", "lotus-tealight-holder", "AC-DY-005", "Diyas & Pooja", 399, 499, 50,
    "Pure white porcelain lotuses that cradle a tealight — calm light for the pooja corner or dining table.",
    [["Material", "Porcelain"], ["Pieces", "Set of 2"], ["Finish", "Glossy White"], ["Fits", "Standard tealight"]]),
  p("Emerald Candle Stand Pair", "emerald-candle-stand-pair", "AC-DY-006", "Diyas & Pooja", 1490, 1790, 12,
    "Tall pierced candle stands in a rich emerald glaze — a striking pair for the mandir or mantel.",
    [["Material", "Ceramic"], ["Pieces", "Set of 2"], ["Height", "22 cm"], ["Finish", "Emerald Glaze"]]),
  p("Celadon Dhoop Bowl", "celadon-dhoop-bowl", "AC-DY-007", "Diyas & Pooja", 699, 849, 25,
    "A footed celadon bowl with relief work for dhoop, sambrani or incense cones — or simply as a small planter.",
    [["Material", "Stoneware"], ["Diameter", "12 cm"], ["Finish", "Celadon Glaze"], ["Usage", "Incense / Dhoop"]]),

  // ------------------------------------------------------- Clay & Earthenware
  p("Green Glazed Matka", "green-glazed-matka", "AC-CE-001", "Clay & Earthenware", 1290, 1590, 15,
    "A round-bellied matka with a mottled green glaze outside and natural clay inside to keep water cool.",
    [["Material", "Terracotta, Glazed Outside"], ["Capacity", "10 litres"], ["Includes", "Lid"], ["Usage", "Water Storage"]], true),
  p("Black Clay Handi", "black-clay-handi", "AC-CE-002", "Clay & Earthenware", 899, 1099, 20,
    "A black-fired clay handi for slow-cooked dal, biryani and curries — the clay adds a gentle earthy flavour.",
    [["Material", "Black Clay"], ["Capacity", "2 litres"], ["Usage", "Cooking / Serving"], ["Care", "Season before first use"]]),
  p("Terracotta Water Matka", "terracotta-water-matka", "AC-CE-003", "Clay & Earthenware", 599, 749, 30,
    "A classic natural-clay matka that cools water the traditional way — no electricity needed.",
    [["Material", "Terracotta"], ["Capacity", "5 litres"], ["Usage", "Water Storage"], ["Care", "Rinse with water only"]]),
  p("Clay Tumbler Set", "clay-tumbler-set", "AC-CE-004", "Clay & Earthenware", 449, 549, 40,
    "Unglazed clay tumblers for chaas, lassi and cool water — earthy, rustic and naturally cooling.",
    [["Material", "Terracotta"], ["Capacity", "250 ml each"], ["Pieces", "Set of 4"], ["Care", "Hand wash only"]]),

  // -------------------------------------------------------------- Cups & Mugs
  p("Nilgiri Brushstroke Mug", "nilgiri-brushstroke-mug", "AC-CM-012", "Cups & Mugs", 549, 699, 30,
    "A tall mug and saucer with free blue-grey brushstrokes on white — every piece painted by hand.",
    [["Material", "Stoneware"], ["Capacity", "350 ml"], ["Pieces", "Mug + Saucer"], ["Finish", "Hand-Painted"]]),
  p("Zigzag Monochrome Mug", "zigzag-monochrome-mug", "AC-CM-013", "Cups & Mugs", 399, 499, 45,
    "Crisp black zigzags on a white mug — modern, graphic and great for everyday coffee.",
    [["Material", "Ceramic"], ["Capacity", "320 ml"], ["Finish", "Glossy Print"], ["Dishwasher Safe", "Yes"]]),
  p("Rosso Cappuccino Cup", "rosso-cappuccino-cup", "AC-CM-014", "Cups & Mugs", 449, 549, 40,
    "A bold red cappuccino cup and saucer with a white interior that shows off latte art.",
    [["Material", "Porcelain"], ["Capacity", "220 ml"], ["Pieces", "Cup + Saucer"], ["Finish", "Glossy Red"]]),
  p("Haathi Cup & Saucer", "haathi-cup-saucer", "AC-CM-015", "Cups & Mugs", 499, 599, 35,
    "A wide tea cup with a hand-painted blue elephant — a playful favourite for evening chai.",
    [["Material", "Ceramic"], ["Capacity", "250 ml"], ["Pieces", "Cup + Saucer"], ["Finish", "Hand-Painted"]], true),
  p("Plum Matte Mug", "plum-matte-mug", "AC-CM-016", "Cups & Mugs", 379, 479, 50,
    "A generous café mug in a deep plum-grey matte finish with a smooth white inside.",
    [["Material", "Ceramic"], ["Capacity", "400 ml"], ["Finish", "Matte Outside, Glossy Inside"], ["Microwave Safe", "Yes"]]),
  p("Pour-Over Stoneware Mug", "pour-over-stoneware-mug", "AC-CM-017", "Cups & Mugs", 449, 549, 35,
    "A chunky hand-thrown mug with a soft grey glaze — made for slow pour-over coffee.",
    [["Material", "Stoneware"], ["Capacity", "300 ml"], ["Finish", "Satin Grey"], ["Dishwasher Safe", "Yes"]]),
  p("Latte Art Cup & Saucer", "latte-art-cup-saucer", "AC-CM-018", "Cups & Mugs", 499, 599, 40,
    "A wide, café-standard white cup with a matching saucer — the shape baristas use for latte art.",
    [["Material", "Porcelain"], ["Capacity", "280 ml"], ["Pieces", "Cup + Saucer"], ["Dishwasher Safe", "Yes"]]),
  p("Teal Rim Cappuccino Cup", "teal-rim-cappuccino-cup", "AC-CM-019", "Cups & Mugs", 449, 549, 40,
    "A cappuccino cup with a teal exterior and white interior, on a matching saucer.",
    [["Material", "Porcelain"], ["Capacity", "200 ml"], ["Pieces", "Cup + Saucer"], ["Finish", "Glossy Teal"]]),
  p("Midnight Latte Cup", "midnight-latte-cup", "AC-CM-020", "Cups & Mugs", 449, 549, 40,
    "A glossy black latte cup and saucer — dramatic against creamy foam.",
    [["Material", "Porcelain"], ["Capacity", "250 ml"], ["Pieces", "Cup + Saucer"], ["Finish", "Glossy Black"]]),

  // ------------------------------------------------------- Tea Sets & Teapots
  p("Koi Gaiwan", "koi-gaiwan", "AC-TS-008", "Tea Sets & Teapots", 799, 999, 20,
    "A lidded tea cup with saucer, painted with a single red koi — brew and sip loose-leaf tea in one piece.",
    [["Material", "Porcelain"], ["Capacity", "150 ml"], ["Pieces", "Bowl + Lid + Saucer"], ["Finish", "Hand-Painted"]]),
  p("Painted Tea Bowl Set", "painted-tea-bowl-set", "AC-TS-009", "Tea Sets & Teapots", 899, 1099, 18,
    "Small handleless tea bowls with fine red brushwork — for green tea, kahwa or espresso shots.",
    [["Material", "Porcelain"], ["Capacity", "80 ml each"], ["Pieces", "Set of 4"], ["Finish", "Hand-Painted"]]),
  p("Celadon Matcha Bowl", "celadon-matcha-bowl", "AC-TS-010", "Tea Sets & Teapots", 899, 1099, 20,
    "A wide, deep bowl in soft celadon, shaped for whisking matcha — also lovely for soups and desserts.",
    [["Material", "Stoneware"], ["Diameter", "12 cm"], ["Finish", "Celadon Glaze"], ["Usage", "Matcha / Serving"]]),
  p("Olive Glaze Tea Bowl", "olive-glaze-tea-bowl", "AC-TS-011", "Tea Sets & Teapots", 799, 949, 15,
    "A hand-thrown tea bowl with an olive-green glaze that breaks brown at the rim.",
    [["Material", "Stoneware"], ["Diameter", "13 cm"], ["Finish", "Olive Glaze"], ["Care", "Hand wash only"]]),

  // -------------------------------------------------------------------- Bowls
  p("Classic Ramen Bowl", "classic-ramen-bowl", "AC-BW-010", "Bowls", 599, 749, 40,
    "A deep white bowl sized for ramen, pho, thukpa and big bowls of Maggi.",
    [["Material", "Ceramic"], ["Capacity", "1.1 litres"], ["Finish", "Glossy White"], ["Microwave Safe", "Yes"]]),
  p("Stoneware Noodle Bowl", "stoneware-noodle-bowl", "AC-BW-011", "Bowls", 649, 799, 30,
    "A dark stoneware noodle bowl with a wide rim that keeps broth hot.",
    [["Material", "Stoneware"], ["Capacity", "1 litre"], ["Finish", "Matte Charcoal"], ["Dishwasher Safe", "Yes"]]),
  p("Everyday Rice Bowl", "everyday-rice-bowl", "AC-BW-012", "Bowls", 699, 849, 50,
    "Simple white bowls for rice, dal and curd — the everyday workhorse of the kitchen.",
    [["Material", "Ceramic"], ["Capacity", "400 ml each"], ["Pieces", "Set of 4"], ["Dishwasher Safe", "Yes"]]),
  p("White Fruit Bowl", "white-fruit-bowl", "AC-BW-013", "Bowls", 549, 699, 35,
    "A clean, deep white bowl for berries, fruit chaat or salads on the go.",
    [["Material", "Ceramic"], ["Diameter", "16 cm"], ["Finish", "Glossy White"], ["Microwave Safe", "Yes"]]),
  p("Red Cereal Bowl", "red-cereal-bowl", "AC-BW-014", "Bowls", 399, 499, 45,
    "A cheerful red bowl for muesli, poha, oats and fruit.",
    [["Material", "Ceramic"], ["Capacity", "600 ml"], ["Finish", "Glossy Red"], ["Dishwasher Safe", "Yes"]]),
  p("Mini Dip Bowl Set", "mini-dip-bowl-set", "AC-BW-015", "Bowls", 499, 599, 40,
    "Small white bowls for chutneys, raita, dips and sauces — great for party platters.",
    [["Material", "Porcelain"], ["Capacity", "80 ml each"], ["Pieces", "Set of 6"], ["Dishwasher Safe", "Yes"]]),
  p("Lal Gulab Bowl", "lal-gulab-bowl", "AC-BW-016", "Bowls", 1290, 1590, 12,
    "A coral-red bowl covered in painted blue and pink peonies — a statement serving bowl for festive tables.",
    [["Material", "Porcelain"], ["Diameter", "20 cm"], ["Finish", "Hand-Painted"], ["Care", "Hand wash only"]], true),
  p("Turquoise Relief Bowl", "turquoise-relief-bowl", "AC-BW-017", "Bowls", 999, 1199, 15,
    "A turquoise-glazed bowl with raised relief work around the sides — beautiful for fruit or as décor.",
    [["Material", "Ceramic"], ["Diameter", "22 cm"], ["Finish", "Turquoise Glaze"], ["Care", "Hand wash only"]]),

  // ------------------------------------------------------------------- Plates
  p("Jaali Rim Plate", "jaali-rim-plate", "AC-PL-006", "Plates", 1190, 1449, 16,
    "A white plate with a pierced jaali border and blue floral centre — for serving mithai or as wall décor.",
    [["Material", "Porcelain"], ["Diameter", "24 cm"], ["Finish", "Blue & White, Pierced Rim"], ["Care", "Hand wash only"]], true),
  p("Blue Onion Plate", "blue-onion-plate", "AC-PL-007", "Plates", 899, 1099, 20,
    "The timeless blue flower-and-vine pattern on a ribbed white plate.",
    [["Material", "Porcelain"], ["Diameter", "25 cm"], ["Finish", "Blue & White"], ["Dishwasher Safe", "Yes"]]),
  p("Blue Willow Plate", "blue-willow-plate", "AC-PL-008", "Plates", 799, 999, 25,
    "A scalloped plate with a classic blue landscape print — mix and match with your blue-and-white collection.",
    [["Material", "Ceramic"], ["Diameter", "25 cm"], ["Finish", "Blue Transfer Print"], ["Dishwasher Safe", "Yes"]]),
  p("White Coupe Plate Set", "white-coupe-plate", "AC-PL-009", "Plates", 1299, 1599, 25,
    "Rimless coupe plates in plain white — the modern restaurant plating look at home.",
    [["Material", "Porcelain"], ["Diameter", "27 cm"], ["Pieces", "Set of 4"], ["Dishwasher Safe", "Yes"]]),
  p("Sky Glaze Pasta Plate", "sky-glaze-pasta-plate", "AC-PL-010", "Plates", 699, 849, 30,
    "A shallow, wide plate in soft sky-blue glaze for pasta, pulao and saucy dishes.",
    [["Material", "Stoneware"], ["Diameter", "24 cm"], ["Finish", "Sky Blue Glaze"], ["Microwave Safe", "Yes"]]),
  p("Hexagon Art Deco Plate", "hexagon-art-deco-plate", "AC-PL-011", "Plates", 799, 949, 20,
    "A six-sided plate with ochre and blue Art Deco panels — a conversation piece for snacks and sweets.",
    [["Material", "Ceramic"], ["Size", "22 cm"], ["Finish", "Hand-Painted"], ["Care", "Hand wash only"]]),
  p("Lattice Rim Dessert Plate", "lattice-rim-dessert-plate", "AC-PL-012", "Plates", 849, 999, 20,
    "A basket-weave rim with painted wildflowers — for cake, pastries and mithai.",
    [["Material", "Porcelain"], ["Diameter", "21 cm"], ["Finish", "Hand-Painted, Embossed Rim"], ["Care", "Hand wash only"]]),

  // -------------------------------------------------------- Decorative Plates
  p("Parrot Garden Plate", "parrot-garden-plate", "AC-DP-007", "Decorative Plates", 1590, 1890, 10,
    "Two painted parrots on a flowering branch within a blue border — a joyful wall plate.",
    [["Material", "Ceramic"], ["Diameter", "26 cm"], ["Finish", "Hand-Painted"], ["Usage", "Décor / Wall Display"]], true),
  p("Hiran Medallion Plate", "hiran-medallion-plate", "AC-DP-008", "Decorative Plates", 1790, 2090, 8,
    "A leaping deer at the centre of bold orange, blue and green borders — rich folk-art colours.",
    [["Material", "Ceramic"], ["Diameter", "28 cm"], ["Finish", "Hand-Painted, Glazed"], ["Usage", "Décor / Wall Display"]]),
  p("Pink Peony Gold Plate", "pink-peony-gold-plate", "AC-DP-009", "Decorative Plates", 1690, 1990, 8,
    "A single pink peony framed by a wide gilded border — elegant for display or gifting.",
    [["Material", "Porcelain"], ["Diameter", "24 cm"], ["Finish", "Hand-Painted with Gold"], ["Usage", "Décor / Gifting"]]),
  p("Green Leaf Sgraffito Plate", "green-leaf-sgraffito-plate", "AC-DP-010", "Decorative Plates", 1390, 1690, 10,
    "Radiating green leaves carved through a cream slip — an earthy, hand-crafted display plate.",
    [["Material", "Stoneware"], ["Diameter", "27 cm"], ["Finish", "Sgraffito"], ["Usage", "Décor / Serving"]]),

  // ------------------------------------------------------------- Serving Ware
  p("Navy Floral Oval Dish", "navy-floral-oval-dish", "AC-SW-017", "Serving Ware", 1490, 1790, 10,
    "An oval dish with a painted bouquet inside a deep navy and gold border.",
    [["Material", "Porcelain"], ["Size", "30 × 22 cm"], ["Finish", "Hand-Painted with Gold"], ["Care", "Hand wash only"]]),
  p("Lace Fruit Basket", "lace-fruit-basket", "AC-SW-018", "Serving Ware", 1290, 1590, 12,
    "A pierced white basket plate that looks like lace — for fruit, bread or dry fruits.",
    [["Material", "Ceramic"], ["Size", "28 cm"], ["Finish", "Pierced White"], ["Care", "Hand wash only"]]),
  p("Mint Cake Stand", "mint-cake-stand", "AC-SW-019", "Serving Ware", 1490, 1790, 12,
    "A footed cake stand in fresh mint — show off cakes, tarts and mithai at celebrations.",
    [["Material", "Ceramic"], ["Diameter", "28 cm"], ["Height", "10 cm"], ["Finish", "Glossy Mint"]], true),
  p("Chutney Dip Platter", "chutney-dip-platter", "AC-SW-020", "Serving Ware", 799, 999, 20,
    "A white platter with three built-in wells for chutneys, hummus and dips.",
    [["Material", "Ceramic"], ["Size", "30 cm"], ["Compartments", "3"], ["Dishwasher Safe", "Yes"]]),
  p("Heritage Lidded Serving Dish", "heritage-lidded-serving-dish", "AC-SW-021", "Serving Ware", 2490, 2990, 8,
    "A grand domed serving dish painted with floral sprays — keeps rotis, biryani or kebabs warm at the table.",
    [["Material", "Porcelain"], ["Size", "32 × 24 cm"], ["Includes", "Dome Lid"], ["Finish", "Hand-Painted"]]),

  // ----------------------------------------------------------- Jars & Storage
  p("Ceramic Honey Pot", "ceramic-honey-pot", "AC-JS-008", "Jars & Storage", 549, 699, 30,
    "A creamy white honey pot with a wooden dipper — also great for ghee or jaggery syrup.",
    [["Material", "Ceramic"], ["Capacity", "350 ml"], ["Includes", "Wooden dipper"], ["Food Safe", "Yes"]]),
  p("Celadon Trinket Box", "celadon-trinket-box", "AC-JS-009", "Jars & Storage", 699, 849, 20,
    "A round lidded box in pale celadon with incised patterns — for jewellery, sindoor or spices.",
    [["Material", "Stoneware"], ["Diameter", "9 cm"], ["Finish", "Celadon Glaze"], ["Usage", "Storage / Gifting"]]),

  // ---------------------------------------------------------- Planters & Pots
  p("Lilac Scallop Planter", "lilac-scallop-planter", "AC-PP-021", "Planters & Pots", 549, 699, 30,
    "A petal-edged planter in soft lilac — pretty with bulbs, hyacinths and flowering plants.",
    [["Material", "Ceramic"], ["Size", "6 inch"], ["Drainage Hole", "Yes"], ["Finish", "Glossy Lilac"]]),
  p("Tangerine Glaze Pot", "tangerine-glaze-pot", "AC-PP-022", "Planters & Pots", 699, 849, 25,
    "A sunny tangerine pot for citrus plants, bonsai and balcony greens.",
    [["Material", "Ceramic"], ["Size", "8 inch"], ["Drainage Hole", "Yes"], ["Finish", "Tangerine Glaze"]]),
  p("Royal Blue Flower Pot", "royal-blue-flower-pot", "AC-PP-023", "Planters & Pots", 799, 949, 25,
    "A deep royal-blue glazed pot that makes pink and white flowers glow.",
    [["Material", "Ceramic"], ["Size", "8 inch"], ["Drainage Hole", "Yes"], ["Usage", "Indoor / Outdoor"]]),
  p("Hands Planter", "hands-planter", "AC-PP-024", "Planters & Pots", 1290, 1590, 12,
    "A sculpted pair of cupped hands that hold your plants — a garden statement piece.",
    [["Material", "Ceramic"], ["Size", "10 inch"], ["Finish", "Matte White"], ["Usage", "Garden / Balcony"]], true),
  p("Heritage Floral Jardinière", "heritage-floral-jardiniere", "AC-PP-025", "Planters & Pots", 1890, 2290, 8,
    "A flared jardinière painted with birds and blossoms — for a prized indoor plant.",
    [["Material", "Porcelain"], ["Size", "10 inch"], ["Finish", "Hand-Painted"], ["Usage", "Indoor"]]),
  p("Speckled Mini Pot", "speckled-mini-pot", "AC-PP-026", "Planters & Pots", 299, 379, 50,
    "A tiny speckled pot for herbs, succulents and desk greens.",
    [["Material", "Stoneware"], ["Size", "3 inch"], ["Finish", "Speckled"], ["Usage", "Desk / Windowsill"]]),

  // ------------------------------------------------------------ Vases & Décor
  p("Celadon Moon Jar", "celadon-moon-jar", "AC-VD-011", "Vases & Décor", 1990, 2390, 8,
    "A full, rounded jar in pale celadon — quiet, sculptural and beautiful on a console.",
    [["Material", "Stoneware"], ["Height", "20 cm"], ["Finish", "Celadon Glaze"], ["Usage", "Décor"]]),
  p("Celadon Crackle Bud Vase", "celadon-crackle-bud-vase", "AC-VD-012", "Vases & Décor", 899, 1099, 15,
    "A slim bottle vase in green crackle glaze, sitting on its own matching dish.",
    [["Material", "Porcelain"], ["Height", "24 cm"], ["Finish", "Crackle Glaze"], ["Usage", "Single Stems / Décor"]]),
  p("Slim White Stem Vase", "slim-white-stem-vase", "AC-VD-013", "Vases & Décor", 599, 749, 30,
    "A tall, narrow white vase for dried gypsophila, pampas or a few fresh stems.",
    [["Material", "Ceramic"], ["Height", "28 cm"], ["Finish", "Matte White"], ["Usage", "Dried / Fresh Flowers"]]),
  p("Mustard Vase", "mustard-vase", "AC-VD-014", "Vases & Décor", 699, 849, 25,
    "A cheerful mustard-yellow vase that loves dried grasses and wildflowers.",
    [["Material", "Ceramic"], ["Height", "20 cm"], ["Finish", "Glossy Mustard"], ["Usage", "Flowers / Décor"]]),
];
